---
- name: Install RPMFusion free packages
  become: true
  ansible.builtin.yum:
    name: "{{ rpmfusion_free_rpm_package_url }}"
    state: present
    disable_gpg_check: true
  when: rpmfusion_free_repository

- name: Install RPMFusion nonfree packages
  become: true
  ansible.builtin.yum:
    name: "{{ rpmfusion_nonfree_rpm_package_url }}"
    state: present
    disable_gpg_check: true
  when: rpmfusion_nonfree_repository

...
